"""
Django settings for excel_form_app project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path  # Import Path class to handle filesystem paths

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent  # Define the base directory of the project

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-mkiu+ph5%jsbi(6+9jhxu)py)en@(h8m=g%ve+z31j&eezkiq9'  # Secret key for cryptographic signing

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True  # Enable debug mode (should be False in production)

ALLOWED_HOSTS = []  # List of hosts/domains the site can serve

# Application definition

INSTALLED_APPS = [  # List of Django apps installed in this project
    'django.contrib.admin',  # Admin interface
    'django.contrib.auth',  # Authentication framework
    'django.contrib.contenttypes',  # Content types framework
    'django.contrib.sessions',  # Session framework
    'django.contrib.messages',  # Messaging framework
    'django.contrib.staticfiles',  # Static files handling
    'main'  # Custom app named "main"
]

MIDDLEWARE = [  # List of middleware classes to process requests/responses
    'django.middleware.security.SecurityMiddleware',  # Security enhancements
    'django.contrib.sessions.middleware.SessionMiddleware',  # Manage sessions
    'django.middleware.common.CommonMiddleware',  # Basic HTTP middleware
    'django.middleware.csrf.CsrfViewMiddleware',  # CSRF protection
    'django.contrib.auth.middleware.AuthenticationMiddleware',  # Authentication handling
    'django.contrib.messages.middleware.MessageMiddleware',  # Message framework
    'django.middleware.clickjacking.XFrameOptionsMiddleware',  # Clickjacking protection
]

ROOT_URLCONF = 'excel_form_app.urls'  # Define the root URL configuration module

TEMPLATES = [  # Template engine configuration
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',  # Use Django template engine
        'DIRS': [BASE_DIR / "templates"],  # Project-level templates directory
        'APP_DIRS': True,  # Enable template discovery in installed apps
        'OPTIONS': {  # Additional template options
            'context_processors': [  # Context processors to inject variables into templates
                'django.template.context_processors.request',  # Add request object
                'django.contrib.auth.context_processors.auth',  # Add user and authentication info
                'django.contrib.messages.context_processors.messages',  # Add messages
            ],
        },
    },
]

WSGI_APPLICATION = 'excel_form_app.wsgi.application'  # WSGI callable for deployment

# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {  # Database connection settings
    'default': {  # Default database
        'ENGINE': 'django.db.backends.postgresql',  # Use PostgreSQL backend
        'NAME': 'db',  # Database name
        'USER': 'postgres',  # Database username
        'PASSWORD': 'your_database_password',  # Database password
        'HOST': 'localhost',  # Database host
        'PORT': '5432',  # Database port
    }
}

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [  # Validators for user passwords
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',  # Prevent passwords similar to user attributes
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',  # Enforce minimum length
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',  # Prevent common passwords
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',  # Prevent fully numeric passwords
    },
]

# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'  # Default language

TIME_ZONE = 'UTC'  # Default time zone

USE_I18N = True  # Enable Django's internationalization system

USE_TZ = True  # Enable timezone-aware datetimes

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'  # URL path for static files
STATICFILES_DIRS = [  # Additional directories to search for static files
    BASE_DIR / "static",  # Project-level static folder
]

LOGIN_REDIRECT_URL = 'home'  # Redirect after successful login
LOGOUT_REDIRECT_URL = 'home'  # Redirect after logout
LOGIN_URL = 'login'  # URL for login page

